In [6]:
from sklearn import preprocessing
import numpy as np
X_train = np.array([[ 1., -1.,  2.],
                    [ 2.,  0.,  0.],
                    [ 0.,  1., -1.]])
scaler = preprocessing.StandardScaler().fit(X_train)
scaler

,copy,True
,with_mean,True
,with_std,True


In [8]:
# mean of each feature (column)
scaler.mean_

array([1.        , 0.        , 0.33333333])

In [9]:
# standard deviation of each feature
scaler.scale_

array([0.81649658, 0.81649658, 1.24721913])

Mean and standard deviation are used to scale the features so that they have zero mean and unit variance, using the formula:
$$ X_{\text{scaled}} = \frac{X - \text{mean}}{\text{scale}} $$

In [10]:
X_scaled = scaler.transform(X_train)
X_scaled

array([[ 0.        , -1.22474487,  1.33630621],
       [ 1.22474487,  0.        , -0.26726124],
       [-1.22474487,  1.22474487, -1.06904497]])

In [11]:
# mean of scaled features; axis = 0 tells function to calculate mean of columns (features)
X_scaled.mean(axis=0)

array([0., 0., 0.])

In [12]:
# standard deviation of scaled features
X_scaled.std(axis=0)

array([1., 1., 1.])

A pipeline is a tool that allows multiple processing steps to be chained together into one unified model. 

`StandardScaler.fit()` is used to learn the mean and standard deviation of the training data.
`StandardScaler.transform()` can then be used to apply the same transformation to the training or the test data. It is important that the scaling rules are learned only from the training data, and not the test data, so that the test data remains truly 'unseen'. 


In [16]:
from sklearn.datasets import make_classification
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler

# create a fake dataset for classification, where X is the input features and y is the corresponding labels
# random_state sets the seed for reproducability
X, y = make_classification(random_state=42)

# splits the dataset into two parts, one for training and one for testing
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)

# creates a pipeline
# the pipeline makes sure the steps happen in the correct order
# the first step uses StandardScaler:
# - learns the mean and standard deviation of X_train
# - scales the data so each feature has mean 0 and variance 1
# the second step uses LogisticRegression:
# - learns how to predict the label (0 or 1) from the scaled features
pipe = make_pipeline(StandardScaler(), LogisticRegression())

# trains the entire pipeline in one command
# internally, it:
# - fits the scaler to learn mean and std: scaler.fit(X_train)
# - transforms the data: X_scaled_train = scaler.transform(X_train)
# - fits (trains) the logistic regression model: logreg.fit(X_scaled_train, y_train)
pipe.fit(X_train, y_train) 

,steps,"[('standardscaler', ...), ('logisticregression', ...)]"
,transform_input,None
,memory,None
,verbose,False
,copy,True
,with_mean,True
,with_std,True
,penalty,'l2'
,dual,False
,tol,0.0001
,C,1.0


In [17]:
# evaluate the pipeline on the test data
# Internally, this does:
# - X_scaled_test = scaler.transform(X_test) using the mean and std learned from X_train
# - y_pred = logreg.predict(X_scaled_test) to predict labels
# - compare y_pred with y_test to calculate accuracy
pipe.score(X_test, y_test)

0.96

An alternate standardisation is scaling features to lie between a minimum and maximum value, often between zero and one, or so that the maximum absolute value of each feature is scaled to unit size. This can be achieved using MinMaxScaler or MaxAbsScaler, respectively.

The motivation to use this scaling includes robustness to very small standard deviations of features and preserving zero entries in sparse data.

In [18]:
X_train = np.array([[ 1., -1.,  2.],
                    [ 2.,  0.,  0.],
                    [ 0.,  1., -1.]])
min_max_scaler = preprocessing.MinMaxScaler()
X_train_minmax = min_max_scaler.fit_transform(X_train)
X_train_minmax

array([[0.5       , 0.        , 1.        ],
       [1.        , 0.5       , 0.33333333],
       [0.        , 1.        , 0.        ]])